import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppProviders } from "../provider";
import "./globals.css";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});



export const metadata: Metadata = {
    title: "B-Harvest FE Homework",
    description: "Generated by Jihwang",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`font-inter ${inter.variable} antialiased`}>
                <AppProviders>
                    <div className="relative mx-auto h-screen bg-black shadow-2xl">

                        {children}

                    {children}
                    </div>
                </AppProviders>
            </body>
        </html>
    );
}
